### ISSUE TITLE
Error: Unable to call api

### ISSUE THREAD

**Issue by ItsNoted** [plutov/formulosity#11]
Using the provided Docker Compose I am getting this error. It will show the main page of the survey but when I press start it gives this error.

![image](https://github.com/user-attachments/assets/18c8b7a6-475b-42fa-a0d7-93e0cd05c4ea)

**Comment by plutov** [comment]
This call is happening from the browser, so probably it's something related to `NEXT_PUBLIC_CONSOLE_API_ADDR`. Can you please confirm that you can get the list of surveys from http://localhost:9900/app/surveys?

**Comment by ItsNoted** [comment]
> [/app/surveys](http://localhost:9900/app/surveys)?

I changed  - UI_ADDR=http://localhost:3000 to ip.of.host:3000

/app/surveys gives 404 not found.

**Comment by plutov** [comment]
Yes, it is in `ui/.env.production` file. I think it could also be related to CORS config. Let me remove it now as it's not needed for self-hosted app and you can try again.

**Comment by plutov** [comment]
Please try now without cors (pull/rebuild)

**Comment by ItsNoted** [comment]
Oh I see. Why not put all the env in the compose rather than some in the compose and some in an env file?

Anyway, I repulled and still having the same issue.

**Comment by plutov** [comment]
@ItsNoted can you please show the console error is there are any?

**Comment by plutov** [comment]
and good point on env vars, will try to keep them in one place.

**Comment by plutov** [comment]
Good news @ItsNoted I refactored env vars, improved cors, removed some redundant env vars. Now everything is in docker-compose. Can you please kindly give it a try one more time?
