### ISSUE TITLE
Add SQLite support

### ISSUE THREAD

**Issue by brtwrst** [plutov/formulosity#14]
Hi,

allowing to use SQLite would simplify the hosting for the app greatly.
SQLite should be more than capable of handling the load if the instance is not extremely big.
see: https://sqlite.org/whentouse.html

Important:
a) enable WAL mode
b) use a single writer Process (works with multiple, but processes should retry if they receive "database is locked" and not error out)
see: https://news.ycombinator.com/item?id=33975635

**Comment by plutov** [comment]
Yes, that would make sense. We can probably still keep Postgres and let user decide what to use to store data.

**Comment by plutov** [comment]
Done in new release!

**Comment by brtwrst** [comment]
Awesome, nice job.

What motivated the change from alpine to debian:bookworm for the base image?

**Comment by plutov** [comment]
Good observation, I think it's needed to work properly with sqlite as it needs cgo. At least for build, but let me test the final stage.

**Comment by plutov** [comment]
ok, for some reason this command doesn't work with alpine:
```
COPY --from=builder /root/api .
```

**Comment by brtwrst** [comment]
I tried it and it worked fine for me
the build step at least.
The resulting image with alpine is quite a bit smaller
![image](https://github.com/user-attachments/assets/b308b303-31c9-44da-8b1b-08816e176c9e)
I did not test any functionality yet though, just pulled the repo, changed the line to
```
FROM alpine:latest
RUN apk --no-cache add ca-certificates tzdata bash sqlite
```
(sqlite is probably not needed as a package)
and built it

**Comment by brtwrst** [comment]
ah
it is making /root/api into a file

**Comment by brtwrst** [comment]
yeah nevermind the file can somehow not be run

**Comment by plutov** [comment]
Awesome, it works perfectly. Just pushed it. Thanks a lot!

**Comment by brtwrst** [comment]
I think you can also shrink the UI image a bit by using the following:
```Dockerfile
FROM node:20-alpine AS base

FROM base AS deps
RUN apk add --no-cache libc6-compat
WORKDIR /app

COPY package.json package-lock.json ./
RUN npm ci

FROM base AS builder
WORKDIR /app
COPY --from=deps /app/node_modules ./node_modules
COPY . .

ENV NODE_ENV=production
ARG NEXT_PUBLIC_CONSOLE_API_ADDR
ENV NEXT_PUBLIC_CONSOLE_API_ADDR=$NEXT_PUBLIC_CONSOLE_API_ADDR

RUN npm run build

FROM alpine:latest AS runner
WORKDIR /app

RUN apk add nodejs npm

ENV NODE_ENV=production

RUN addgroup --system --gid 1001 nodejs
RUN adduser --system --uid 1001 nextjs

COPY --from=builder /app/public ./public

RUN mkdir .next
RUN chown nextjs:nodejs .next

COPY --from=builder --chown=nextjs:nodejs /app/.next/standalone ./
COPY --from=builder --chown=nextjs:nodejs /app/.next/static ./.next/static

USER nextjs

EXPOSE 3000

ENV PORT=3000

CMD ["node", "server.js"]

```

This also means that both images can run on base alpine which should make combining them quite simple

**Comment by plutov** [comment]
That looks good, can you submit it as a PR please?
I am thinking to keep 2 separate Dockerfiles still, as people still may want to deploy them separately. But also in root folder create a combined Dockerfile.
