### ISSUE TITLE
Provide prebuilt container image

### ISSUE THREAD

**Issue by brtwrst** [plutov/formulosity#15]
Providing a prebuilt container image will simplify the hosting experience greatly.
Images can be hosted at for Example:  Dockerhub or ghcr.io
see: https://docs.github.com/en/packages/working-with-a-github-packages-registry/working-with-the-container-registry

Further consideration could be given to:
a) Combining the front and backend into a single image
b) Offering SQLite support within the provided image (https://github.com/plutov/formulosity/issues/14)
c) Offering images for ARM based processors, not only x86.
d) Offering non-root variants or making the image non-root by default.

**Comment by plutov** [comment]
Good idea, I may explore how to combine it under a single image. And makes sense on making it availably in the registry.

**Comment by brtwrst** [comment]
so what's the verdict?

**Comment by plutov** [comment]
@brtwrst I am doing sqlite for now and did some refactoring on codebase that will simplify a single docker image later.

**Comment by brtwrst** [comment]
Awesome,

it seems to easily be possible to run both containers on "stock alpine" see here: https://github.com/plutov/formulosity/issues/14#issuecomment-2284812927 and that should make combining them easier and result in a relatively small image (less than 100MB) although that can potentially be reduced even further by some Dockerfile magic.

**Comment by plutov** [comment]
@brtwrst I found a way not to use build args but only runtime env vars. Pushed it into a new release.

**Comment by brtwrst** [comment]
awesome,
If this work with CONSOLE_API_ADDR pointing to a subpath (https://site.com/api for example) then it might be possible to run both over the same port and add nginx or something similar to the image and send the requests to the corresponding service internally.

But running nginx as a non root user always creates some problems so I have to look into that more thoroughly first.

**Comment by anarion80** [comment]
Hello @plutov. So are the prebuilt images available somewhere already?
