### ISSUE TITLE
Bug/UI | Pressing enter on any input screen refreshes the page

### ISSUE THREAD

**Issue by anveshthakur** [plutov/formulosity#22]
Hi @plutov, 

I've encountered an issue where, after entering a value in any of the answer input fields and pressing the "Enter" key to submit, the page refreshes without saving or submitting the input.

Expected behavior: Pressing "Enter" should submit the input or nothing should happen, not cause the page to refresh.

**Comment by anveshthakur** [comment]
Let me know If I can take this up, Thanks! :)

**Comment by plutov** [comment]
Let's validate/submit the form on Enter, good catch.

**Comment by anveshthakur** [comment]
Thanks! I will work on it.

**Comment by plutov** [comment]
done
