### ISSUE TITLE
Bug: Email is not stored or not shown on the Responses tab

### ISSUE THREAD

**Issue by plutov** [plutov/formulosity#23]
<img width="1029" alt="Screenshot 2024-09-27 at 23 23 54" src="https://github.com/user-attachments/assets/397deea8-67ba-4d6e-91c5-ee761150e2ce">

**Comment by plutov** [comment]
cc @anveshthakur

**Comment by anveshthakur** [comment]
I don’t know how I missed it, I am on it!

**Comment by plutov** [comment]
@anveshthakur no worries, you're new to the project.

**Comment by plutov** [comment]
done
