### ISSUE TITLE
The official website prompts for user credentials

### ISSUE THREAD

**Issue by CODERPP10** [plutov/formulosity#35]
The official website of formulosity as added on this repository prompts for user credentials to access it:

![image](https://github.com/user-attachments/assets/743e944a-e63e-466f-a9ce-a90c367ba4be)

**Comment by CODERPP10** [comment]
Hey @brtwrst @jacksonwun @krishnateja262 @plutov,  can anyone explain this?

**Comment by plutov** [comment]
@CODERPP10 yes, that's expected, you can find the credentials in the README
